import { ProductCard } from "./ProductCard/ProductCard";
import { getClasses } from "./ProductListStyle";

const ProductList = () => {
  const classes = getClasses();

  const products = [
    {
      id: 2,
      name: "טלפון",
      catagory: "חמשל",
      description: "גרכחעימגקלחדמכלךדכךדגל",
      location: "ראשון לציון",
      picture: "https://www.pelephone.co.il/ds/uploadedimages/09_2022/iphone_14_pro_max_space_black.png",
      date: "2020",
    },
    {
      id: 2,
      name: "טלפון",
      catagory: "חמשל",
      description: "גרכחעימגקלחדמכלךדכךדגל",
      location: "ראשון לציון",
      picture: "https://www.pelephone.co.il/ds/uploadedimages/09_2022/iphone_14_pro_max_space_black.png",
      date: "2020",
    },
    {
      id: 2,
      name: "טלפון",
      catagory: "חמשל",
      description: "גרכחעימגקלחדמכלךדכךדגל",
      location: "ראשון לציון",
      picture: "https://www.pelephone.co.il/ds/uploadedimages/09_2022/iphone_14_pro_max_space_black.png",
      date: "2020",
    },
    {
      id: 2,
      name: "טלפון",
      catagory: "חמשל",
      description: "גרכחעימגקלחדמכלךדכךדגל",
      location: "ראשון לציון",
      picture: "https://www.pelephone.co.il/ds/uploadedimages/09_2022/iphone_14_pro_max_space_black.png",
      date: "2020",
    },
    {
      id: 2,
      name: "טלפון",
      catagory: "חמשל",
      description: "גרכחעימגקלחדמכלךדכךדגל",
      location: "ראשון לציון",
      picture: "https://www.pelephone.co.il/ds/uploadedimages/09_2022/iphone_14_pro_max_space_black.png",
      date: "2020",
    },
    {
      id: 2,
      name: "טלפון",
      catagory: "חמשל",
      description: "גרכחעימגקלחדמכלךדכךדגל",
      location: "ראשון לציון",
      picture: "https://www.pelephone.co.il/ds/uploadedimages/09_2022/iphone_14_pro_max_space_black.png",
      date: "2020",
    },
    {
      id: 2,
      name: "טלפון",
      catagory: "חמשל",
      description: "גרכחעימגקלחדמכלךדכךדגל",
      location: "ראשון לציון",
      picture: "https://www.pelephone.co.il/ds/uploadedimages/09_2022/iphone_14_pro_max_space_black.png",
      date: "2020",
    },
    {
      id: 2,
      name: "טלפון",
      catagory: "חמשל",
      description: "גרכחעימגקלחדמכלךדכךדגל",
      location: "ראשון לציון",
      picture: "https://www.pelephone.co.il/ds/uploadedimages/09_2022/iphone_14_pro_max_space_black.png",
      date: "2020",
    },
    {
      id: 2,
      name: "טלפון",
      catagory: "חמשל",
      description: "גרכחעימגקלחדמכלךדכךדגל",
      location: "ראשון לציון",
      picture: "https://www.pelephone.co.il/ds/uploadedimages/09_2022/iphone_14_pro_max_space_black.png",
      date: "2020",
    },
    {
      id: 2,
      name: "טלפון",
      catagory: "חמשל",
      description: "גרכחעימגקלחדמכלךדכךדגל",
      location: "ראשון לציון",
      picture: "https://www.pelephone.co.il/ds/uploadedimages/09_2022/iphone_14_pro_max_space_black.png",
      date: "2020",
    },
    {
      id: 2,
      name: "טלפון",
      catagory: "חמשל",
      description: "גרכחעימגקלחדמכלךדכךדגל",
      location: "ראשון לציון",
      picture: "https://www.pelephone.co.il/ds/uploadedimages/09_2022/iphone_14_pro_max_space_black.png",
      date: "2020",
    },
    {
      id: 2,
      name: "טלפון",
      catagory: "חמשל",
      description: "גרכחעימגקלחדמכלךדכךדגל",
      location: "ראשון לציון",
      picture: "https://www.pelephone.co.il/ds/uploadedimages/09_2022/iphone_14_pro_max_space_black.png",
      date: "2020",
    },
    {
      id: 2,
      name: "טלפון",
      catagory: "חמשל",
      description: "גרכחעימגקלחדמכלךדכךדגל",
      location: "ראשון לציון",
      picture: "https://www.pelephone.co.il/ds/uploadedimages/09_2022/iphone_14_pro_max_space_black.png",
      date: "2020",
    },
    {
      id: 2,
      name: "טלפון",
      catagory: "חמשל",
      description: "גרכחעימגקלחדמכלךדכךדגל",
      location: "ראשון לציון",
      picture: "https://www.pelephone.co.il/ds/uploadedimages/09_2022/iphone_14_pro_max_space_black.png",
      date: "2020",
    },
    {
      id: 2,
      name: "טלפון",
      catagory: "חמשל",
      description: "גרכחעימגקלחדמכלךדכךדגל",
      location: "ראשון לציון",
      picture: "https://www.pelephone.co.il/ds/uploadedimages/09_2022/iphone_14_pro_max_space_black.png",
      date: "2020",
    },
    {
      id: 2,
      name: "טלפון",
      catagory: "חמשל",
      description: "גרכחעימגקלחדמכלךדכךדגל",
      location: "ראשון לציון",
      picture: "https://www.pelephone.co.il/ds/uploadedimages/09_2022/iphone_14_pro_max_space_black.png",
      date: "2020",
    },
    {
      id: 2,
      name: "טלפון",
      catagory: "חמשל",
      description: "גרכחעימגקלחדמכלךדכךדגל",
      location: "ראשון לציון",
      picture: "https://www.pelephone.co.il/ds/uploadedimages/09_2022/iphone_14_pro_max_space_black.png",
      date: "2020",
    },
    {
      id: 2,
      name: "טלפון",
      catagory: "חמשל",
      description: "גרכחעימגקלחדמכלךדכךדגל",
      location: "ראשון לציון",
      picture: "https://www.pelephone.co.il/ds/uploadedimages/09_2022/iphone_14_pro_max_space_black.png",
      date: "2020",
    },
    {
      id: 2,
      name: "טלפון",
      catagory: "חמשל",
      description: "המוצר ממש שווה תקחו אותי",
      location: "ראשון לציון",
      picture: "https://www.pelephone.co.il/ds/uploadedimages/09_2022/iphone_14_pro_max_space_black.png",
      date: "2020",
    },
    {
      id: 2,
      name: "טלפון",
      catagory: "חמשל",
      description: "גרכחעימגקלחדמכלךדכךדגל",
      location: "ראשון לציון",
      picture: "https://www.pelephone.co.il/ds/uploadedimages/09_2022/iphone_14_pro_max_space_black.png",
      date: "2020",
    },
    {
      id: 2,
      name: "טלפון",
      catagory: "חמשל",
      description: "גרכחעימגקלחדמכלךדכךדגל",
      location: "ראשון לציון",
      picture: "https://www.pelephone.co.il/ds/uploadedimages/09_2022/iphone_14_pro_max_space_black.png",
      date: "2020",
    },
  ];

  return (
    <div className={classes.productList}>
      {products.map((product) => (
        <ProductCard {...product} />
      ))}
    </div>
  );
};

export default ProductList;
